Algorithm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('App.urls', namespace='App')),
]

App/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from . import views


urlpatterns = [
    # Index
    url(r'^$', views.index, name='index'),
    # Pages
    url(r'^binary_search', views.binary_search, name='binary_search'),
]

App/models.py
from django.db import models

# Create your models here.

App/views.py
from django.shortcuts import render
from .functions import binarySearch

def index(request): return render(request, 'App/index.html')

def binary_search(request):

    context = {}

    return render(request, 'App/binary_search.html', context)

templates/App/binary_search.html
{% extends 'base.html' %}

{% block content %}

    {% load staticfiles %}

    <h3>二分查找</h3>
    <p>用途: 在一个列表中快速查找目标</p>
    <p>需要: 有序的元素列表</p>
    <p>代码:</p>
    <div>
    <script src="{% static 'code/BinarySearch.py' %}"></script>
    </div>

{% endblock %}

templates/App/index.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <h3>Python算法合集</h3>
    <li>
        <a href="{% url 'App:binary_search' %}">二分查找</a>
    </li>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style type="text/css">
       div{
           margin: 8px;
       }
    </style>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <title>Algorithm</title>
</head>
<body>

    <a href="{% url 'App:index' %}">Index</a>

    {% block content %}
    {% endblock %}

</body>
</html>